-- Add new FlashShipmentStatus enum values
ALTER TYPE "FlashShipmentStatus" ADD VALUE IF NOT EXISTS 'AVAILABLE';
ALTER TYPE "FlashShipmentStatus" ADD VALUE IF NOT EXISTS 'ACCEPTED_BY_DRIVER';
ALTER TYPE "FlashShipmentStatus" ADD VALUE IF NOT EXISTS 'DRIVER_EN_ROUTE_TO_PICKUP';
ALTER TYPE "FlashShipmentStatus" ADD VALUE IF NOT EXISTS 'PACKAGE_PICKED_UP';
ALTER TYPE "FlashShipmentStatus" ADD VALUE IF NOT EXISTS 'RETURNED_TO_SELLER';
